settings:
  debug: false
  language: tr

commands:
  main-command: farmer

hooks:
  region:
    provider: SKYLLIA
    skyllia:
      allow-trusted-players: true
      require-skyblock-world: true
      sync-members-on-open: true

database:
  type: SQLITE
  sqlite:
    file: "craftionfarmer.db"
  mysql:
    host: "localhost"
    port: 3306
    database: "craftionfarmer"
    username: "root"
    password: ""
    pool-size: 10
