name: CraftionFarmer
version: 1.0.0-SNAPSHOT
main: com.craftion.farmer.CraftionFarmerPlugin
api-version: "1.21"
folia-supported: true
authors:
  - Craftion
description: CraftionFarmer ana eklentisi
commands:
  farmer:
    description: CraftionFarmer ana komutu
    aliases: [ciftci, "çiftçi"]
permissions:
  craftionfarmer.use:
    default: true
  craftionfarmer.create:
    default: true
  craftionfarmer.remove:
    default: true
  craftionfarmer.admin:
    default: op
  craftionfarmer.admin.bypass:
    default: op
  craftionfarmer.admin.reload:
    default: op
  craftionfarmer.admin.reconcile:
    default: op
dependencies:
  server:
    Skyllia:
      load: BEFORE
      required: false
      join-classpath: true
    FancyNpcs:
      load: BEFORE
      required: false
      join-classpath: true
    Vault:
      load: BEFORE
      required: false
      join-classpath: true
    PlaceholderAPI:
      load: AFTER
      required: false
      join-classpath: true
